# Site Settings
lang: en
title: SOS
tagline: Scientific Computing for Earth Observation and Sustainability
email: samuel.kounev@uni-wuerzburg.de
description: >
  DFG Research Unit - Scientific Computing for Earth Observation and Sustainability (SOS)
baseurl: "/"
url: "https://dfg-sos.de"
permalink: pretty
favicon: /favicon.png
hide_share_buttons: true
force_theme: light

# paginate: 5
# paginate_path: "/blog/page:num"
pagination:
   enabled: true
   per_page: 5
   sort_field: 'date'
   sort_reverse: true

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname:


plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-scholar

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

scholar:
  style: /_bibliography/ieee.csl
  locale: en

scholar_papers:
  bibliography: _bibliography/papers.bib
  style: /_bibliography/ieee.csl

scholar_talks:
  bibliography: _bibliography/talks.bib
  style: /_bibliography/ieee.csl


sass:
  style: compressed
  source_dir: _sass
  # load_paths:
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
    values:
      hero_height: is-small

  # -
  #   scope:
  #     path: ""
  #     type: "pages"
  #   values:
  #     show_sidebar: true
  # -
  #   scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     author: "C.S. Rhymes"
  #     layout: post
  #     image: https://via.placeholder.com/1200x800
  #     show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

# collections:
#   products:
#     output: true
#     layout: product
#     image: https://via.placeholder.com/800x600
#     show_sidebar: false

social:
  #facebook: https://www.facebook.com/
  #instagram: https://www.instagram.com/
  #threads: https://www.threads.net/
  #tiktok: https://www.tiktok.com/
  #x: https://www.x.com/
  #youtube: https://www.youtube.com/
  #linkedin: https://linkedin.com


